### ISSUE TITLE
I can't pip install aldryn-style

### ISSUE THREAD

**Issue by northben** [aldryn/aldryn-style#7]
I've been able to pip install everything else related to django-cms, but this package is not working.

```> pip install aldryn-style```
```Collecting aldryn-style
  Could not find a version that satisfies the requirement aldryn-style (from versions: )
  No matching distribution found for aldryn-style```

**Comment by mkoistinen** [comment]
It doesn't seem to be released to PyPI yet, but you can:
`pip install https://github.com/aldryn/aldryn-style/archive/master.zip`

**Comment by Lionardo** [comment]
There is a release on PyPI now.
